# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='foodbank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_requests', to='login.User'),
        ),
    ]
