# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20161120_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='donor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_offers', to='login.User'),
        ),
    ]
